// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC4DRJn_znEErYKG6d7xqQvpxMuhrAkFA',
    appId: '1:927626904410:web:fbbe7f4893a7b88ef72963',
    messagingSenderId: '927626904410',
    projectId: 'taskapp-ad534',
    authDomain: 'taskapp-ad534.firebaseapp.com',
    storageBucket: 'taskapp-ad534.appspot.com',
    measurementId: 'G-JFSXG8J16F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2oDhhAXUajl5Yi9wWwMsnLKsvTnRLlQ',
    appId: '1:927626904410:android:88bb1af2eb0e6290f72963',
    messagingSenderId: '927626904410',
    projectId: 'taskapp-ad534',
    storageBucket: 'taskapp-ad534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5dD5SgDyN6rMQP2yD7zfp0tosfVWjM4',
    appId: '1:927626904410:ios:972b04c62826d2fcf72963',
    messagingSenderId: '927626904410',
    projectId: 'taskapp-ad534',
    storageBucket: 'taskapp-ad534.appspot.com',
    iosClientId: '927626904410-6p5ah6tj63kd2uspaobudnt9k99qit3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH5dD5SgDyN6rMQP2yD7zfp0tosfVWjM4',
    appId: '1:927626904410:ios:28cc003bdb80b8bff72963',
    messagingSenderId: '927626904410',
    projectId: 'taskapp-ad534',
    storageBucket: 'taskapp-ad534.appspot.com',
    iosClientId: '927626904410-qm58im6eufcc9q2bbjmtpei96377v89v.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
